# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 806cfdfec85b960296c7f90916df6a6f91ed929badc0bd269f2385824ea2b0030518fc92f5ffcb3559a29cabd618723229958fa69ae4b8bbef0379639cef193e

test:
  secret_key_base: 870d184847ea1663fbfabf0656262b9f6839a51660dad5d5df387edfaf67d4fe8726f395a59f845e521846f59cc6c9daf772475957fb4773582471111dfd450f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
